import { Schema } from "effect";
import {
  AddInitiativeUpdateRequestInput,
  AddLinkedRecordInput,
  ArchiveIssueInput,
  AutomationEvaluateIssuesInput,
  AutomationEvaluateQueryInput,
  AutomationEvaluateRepositoryInput,
  CreateDraftInput,
  CreateIssueInput,
  CreateIssueTemplateInput,
  CreateSavedViewInput,
  DeleteIssueInput,
  EmptyInput,
  IssueDiffInput,
  IssueHistoryInput,
  IssueIdInput,
  IssueTemplateQuery,
  IssueQuery,
  IssueRevisionInput,
  LabelDefinitionQuery,
  LabelIdInput,
  RecordsForIssueInput,
  RelationIssueInput,
  RepositoryHistoryInput,
  RepositoryOpenInput,
  RepositoryScoped,
  RestoreIssueInput,
  SavedViewQuery,
  SearchTicketsInput,
  TemplateIdInput,
  TransitionIssueInput,
  UpdateDraftInput,
  UpdateIssueRequestInput,
  UpdateTemplateRequestInput,
  UpdateViewRequestInput,
  UpsertLabelInput,
  UpsertUserInput,
  UserProfileQuery,
  ViewIdInput,
} from "../schemas/index.ts";
import type { UseCaseContract, UseCaseName } from "./Types.ts";

const FailureSchema = Schema.Struct({
  _tag: Schema.String,
  code: Schema.optional(Schema.String),
  details: Schema.optional(Schema.Record(Schema.String, Schema.Unknown)),
  field: Schema.optional(Schema.String),
  message: Schema.String,
  repositoryId: Schema.optional(Schema.String),
  requestId: Schema.String,
  retryable: Schema.Boolean,
  ticketId: Schema.optional(Schema.String),
  useCase: Schema.String,
});

const UnknownSuccess = Schema.Unknown;
const UnknownArraySuccess = Schema.Array(Schema.Unknown);
const UnknownPageSuccess = Schema.Struct({
  entries: Schema.Array(Schema.Unknown),
  nextCursor: Schema.optional(Schema.String),
});
const RepositoryScopedEmpty = RepositoryScoped(EmptyInput);
const RepositoryScopedString = RepositoryScoped(Schema.String);
const RepositoryScopedIssueId = RepositoryScoped(
  Schema.Struct({
    id: Schema.String,
  }),
);

const contract = <Name extends UseCaseName>(
  input: Omit<UseCaseContract<Name>, "failureSchema" | "version">,
): UseCaseContract<Name> => ({
  ...input,
  failureSchema: FailureSchema,
  version: "0.1.0",
});

export const UseCaseContracts = {
  RepositoryOpen: contract({
    aliases: [],
    category: "repository",
    description: "Open or register a repository with the Cycle read model.",
    idempotency: "supported",
    inputSchema: RepositoryOpenInput,
    name: "RepositoryOpen",
    repositoryScope: "single",
    sideEffect: "sync",
    successSchema: UnknownSuccess,
  }),
  RepositoryClose: contract({
    aliases: [],
    category: "repository",
    description: "Close an opened repository.",
    idempotency: "supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryClose",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: Schema.Undefined,
  }),
  RepositoryList: contract({
    aliases: ["repository.status.list"],
    category: "repository",
    description: "List repository statuses.",
    idempotency: "read-only",
    inputSchema: EmptyInput,
    name: "RepositoryList",
    repositoryScope: "none",
    sideEffect: "read",
    successSchema: UnknownArraySuccess,
  }),
  RepositoryStatusGet: contract({
    aliases: ["repository.status.get"],
    category: "repository",
    description: "Read one repository status.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryStatusGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownSuccess,
  }),
  RepositoryMaterializationWarningsList: contract({
    aliases: ["repository.materializationWarnings"],
    category: "repository",
    description: "List materialization warnings for a repository.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryMaterializationWarningsList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownArraySuccess,
  }),
  RepositorySync: contract({
    aliases: ["repository.sync"],
    category: "repository",
    description: "Synchronize the local repository projection.",
    idempotency: "supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositorySync",
    repositoryScope: "single",
    sideEffect: "sync",
    successSchema: UnknownSuccess,
  }),
  RepositoryPush: contract({
    aliases: ["repository.push"],
    category: "repository",
    description: "Push Cycle refs for a repository.",
    idempotency: "not-supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryPush",
    repositoryScope: "single",
    sideEffect: "push",
    successSchema: UnknownSuccess,
  }),
  RepositoryHistoryList: contract({
    aliases: ["repository.history.list"],
    category: "repository",
    description: "List repository history commits.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(RepositoryHistoryInput),
    name: "RepositoryHistoryList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  IssueCreate: contract({
    aliases: ["ticket.issue.create"],
    category: "issue",
    description: "Create a committed issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(CreateIssueInput),
    name: "IssueCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueGet: contract({
    aliases: ["ticket.issue.get"],
    category: "issue",
    description: "Read one issue.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueIdInput),
    name: "IssueGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(Schema.Unknown),
  }),
  IssueList: contract({
    aliases: ["ticket.issue.list"],
    category: "issue",
    description: "List issues.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueQuery),
    name: "IssueList",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  IssueSearch: contract({
    aliases: ["ticket.issue.search"],
    category: "issue",
    description: "Search issues.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(SearchTicketsInput),
    name: "IssueSearch",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  IssueUpdate: contract({
    aliases: ["ticket.issue.update"],
    category: "issue",
    description: "Update issue frontmatter or body.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpdateIssueRequestInput),
    name: "IssueUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueTransition: contract({
    aliases: ["ticket.issue.transition"],
    category: "issue",
    description: "Transition issue status.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(TransitionIssueInput),
    name: "IssueTransition",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueArchive: contract({
    aliases: ["ticket.issue.archive"],
    category: "issue",
    description: "Archive an issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(ArchiveIssueInput),
    name: "IssueArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueRestore: contract({
    aliases: ["ticket.issue.restore"],
    category: "issue",
    description: "Restore an archived or deleted issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(RestoreIssueInput),
    name: "IssueRestore",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueDelete: contract({
    aliases: ["ticket.issue.delete"],
    category: "issue",
    description: "Soft-delete an issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(DeleteIssueInput),
    name: "IssueDelete",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueHistoryList: contract({
    aliases: ["ticket.issue.history"],
    category: "issue",
    description: "List issue history commits.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueHistoryInput),
    name: "IssueHistoryList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  IssueRevisionGet: contract({
    aliases: ["ticket.issue.revision.get"],
    category: "issue",
    description: "Read an issue at a snapshot.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueRevisionInput),
    name: "IssueRevisionGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(Schema.Unknown),
  }),
  IssueDiff: contract({
    aliases: ["ticket.issue.diff"],
    category: "issue",
    description: "Read an issue diff between two snapshots.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueDiffInput),
    name: "IssueDiff",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownSuccess,
  }),
  IssueRelationAdd: contract({
    aliases: ["ticket.issue.relation.add"],
    category: "issue",
    description: "Add an issue relation.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(RelationIssueInput),
    name: "IssueRelationAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  IssueRelationRemove: contract({
    aliases: ["ticket.issue.relation.remove"],
    category: "issue",
    description: "Remove an issue relation.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(RelationIssueInput),
    name: "IssueRelationRemove",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  DraftCreate: contract({
    aliases: ["ticket.draft.create"],
    category: "draft",
    description: "Create a draft issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(CreateDraftInput),
    name: "DraftCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  DraftUpdate: contract({
    aliases: ["ticket.draft.update"],
    category: "draft",
    description: "Update a draft issue.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpdateDraftInput),
    name: "DraftUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  DraftCommit: contract({
    aliases: ["ticket.draft.commit"],
    category: "draft",
    description: "Commit a draft issue.",
    idempotency: "supported",
    inputSchema: RepositoryScopedString,
    name: "DraftCommit",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  CommentAdd: contract({
    aliases: [],
    category: "record",
    description: "Add a user-visible issue comment.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(
      Schema.Struct({
        body: Schema.String,
        issueId: Schema.String,
      }),
    ),
    name: "CommentAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  RecordAdd: contract({
    aliases: ["ticket.record.add"],
    category: "record",
    description: "Add a linked record.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(AddLinkedRecordInput),
    name: "RecordAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  RecordListForIssue: contract({
    aliases: ["ticket.record.listForIssue"],
    category: "record",
    description: "List records for an issue.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(RecordsForIssueInput),
    name: "RecordListForIssue",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  InitiativeCreate: contract({
    aliases: ["ticket.initiative.create"],
    category: "initiative",
    description: "Create an initiative.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(CreateIssueInput),
    name: "InitiativeCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  InitiativeProgressGet: contract({
    aliases: ["ticket.initiative.progress"],
    category: "initiative",
    description: "Read initiative progress.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedIssueId,
    name: "InitiativeProgressGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownSuccess,
  }),
  InitiativeUpdateAdd: contract({
    aliases: ["ticket.initiative.update.add"],
    category: "initiative",
    description: "Add an initiative update.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(AddInitiativeUpdateRequestInput),
    name: "InitiativeUpdateAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  LabelList: contract({
    aliases: ["ticket.label.list"],
    category: "label",
    description: "List labels.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(LabelDefinitionQuery),
    name: "LabelList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  LabelUpsert: contract({
    aliases: ["ticket.label.upsert"],
    category: "label",
    description: "Create or update a label.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpsertLabelInput),
    name: "LabelUpsert",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  LabelArchive: contract({
    aliases: ["ticket.label.archive"],
    category: "label",
    description: "Archive a label.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(LabelIdInput),
    name: "LabelArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  UserGet: contract({
    aliases: ["ticket.user.get"],
    category: "user",
    description: "Read one user.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedString,
    name: "UserGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(Schema.Unknown),
  }),
  UserList: contract({
    aliases: ["ticket.user.list"],
    category: "user",
    description: "List users.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(UserProfileQuery),
    name: "UserList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  UserUpsert: contract({
    aliases: ["ticket.user.upsert"],
    category: "user",
    description: "Create or update a user.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpsertUserInput),
    name: "UserUpsert",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  ViewCreate: contract({
    aliases: ["ticket.view.create"],
    category: "view",
    description: "Create a saved view.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(CreateSavedViewInput),
    name: "ViewCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  ViewGet: contract({
    aliases: ["ticket.view.get"],
    category: "view",
    description: "Read one saved view.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(ViewIdInput),
    name: "ViewGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(Schema.Unknown),
  }),
  ViewList: contract({
    aliases: ["ticket.view.list"],
    category: "view",
    description: "List saved views.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(SavedViewQuery),
    name: "ViewList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  ViewUpdate: contract({
    aliases: ["ticket.view.update"],
    category: "view",
    description: "Update a saved view.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpdateViewRequestInput),
    name: "ViewUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  ViewDelete: contract({
    aliases: ["ticket.view.delete"],
    category: "view",
    description: "Delete a saved view.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(ViewIdInput),
    name: "ViewDelete",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  TemplateCreate: contract({
    aliases: ["ticket.template.create"],
    category: "template",
    description: "Create an issue template.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(CreateIssueTemplateInput),
    name: "TemplateCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  TemplateGet: contract({
    aliases: ["ticket.template.get"],
    category: "template",
    description: "Read one issue template.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(TemplateIdInput),
    name: "TemplateGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(Schema.Unknown),
  }),
  TemplateList: contract({
    aliases: ["ticket.template.list"],
    category: "template",
    description: "List issue templates.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueTemplateQuery),
    name: "TemplateList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UnknownPageSuccess,
  }),
  TemplateUpdate: contract({
    aliases: ["ticket.template.update"],
    category: "template",
    description: "Update an issue template.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(UpdateTemplateRequestInput),
    name: "TemplateUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  TemplateArchive: contract({
    aliases: ["ticket.template.archive"],
    category: "template",
    description: "Archive an issue template.",
    idempotency: "supported",
    inputSchema: RepositoryScoped(TemplateIdInput),
    name: "TemplateArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UnknownSuccess,
  }),
  AutomationEvaluateRepository: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate repository-level automation checks.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateRepositoryInput,
    name: "AutomationEvaluateRepository",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: UnknownSuccess,
  }),
  AutomationEvaluateIssues: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate automation checks for explicit issues.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateIssuesInput,
    name: "AutomationEvaluateIssues",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: UnknownSuccess,
  }),
  AutomationEvaluateQuery: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate automation checks for a query.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateQueryInput,
    name: "AutomationEvaluateQuery",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: UnknownSuccess,
  }),
} as const satisfies Record<UseCaseName, UseCaseContract>;

const AliasEntries = Object.values(UseCaseContracts).flatMap((contract) =>
  contract.aliases.map((alias) => [alias, contract.name] as const),
);

export const UseCaseAliases = new Map<string, UseCaseName>(AliasEntries);

export const contractFor = (name: UseCaseName): UseCaseContract => UseCaseContracts[name];

export const useCaseNameForAlias = (alias: string): UseCaseName | null =>
  UseCaseAliases.get(alias) ?? null;
