import { Schema } from "effect";
import {
  AddInitiativeUpdateRequestInput,
  AddLinkedRecordInput,
  ArchiveIssueInput,
  AutomationEvaluateIssuesInput,
  AutomationEvaluateQueryInput,
  AutomationEvaluateRepositoryInput,
  CreateDraftInput,
  CreateIssueInput,
  CreateIssueTemplateInput,
  CreateSavedViewInput,
  DeleteIssueInput,
  EmptyInput,
  InboxMutationInput,
  InboxPage,
  InboxQuery,
  InboxSummary,
  InboxMutationResult,
  InboxSummaryQuery,
  IssueDiffInput,
  IssueHistoryInput,
  IssueIdInput,
  IssueTemplateQuery,
  IssueQuery,
  IssueRevisionInput,
  LabelDefinitionQuery,
  LabelIdInput,
  RecordsForIssueInput,
  RelationIssueInput,
  RepositoryHistoryInput,
  RepositoryOpenInput,
  RestoreIssueInput,
  SavedViewQuery,
  SearchTicketsInput,
  TemplateIdInput,
  TransitionIssueInput,
  UpdateDraftInput,
  UpdateIssueRequestInput,
  UpdateTemplateRequestInput,
  UpdateViewRequestInput,
  UpsertLabelInput,
  UpsertUserInput,
  UserProfileQuery,
  ViewIdInput,
  AutomationEvaluation,
  HistoryPage,
  InitiativeProgress,
  IssueRelation,
  IssueTemplateDocument,
  IssueTemplatePage,
  LabelDefinitionDocument,
  LabelDefinitionPage,
  LinkedRecord,
  MaterializationWarning,
  RecordPage,
  RepositoryStatus,
  SavedViewDocument,
  SavedViewPage,
  SyncResult,
  TicketDocument,
  TicketDraftDocument,
  TicketPage,
  TicketRevisionDiff,
  TicketSearchPage,
  UserProfileDocument,
  UserProfilePage,
} from "@cycle/contracts/schemas";
import { RepositoryScoped } from "../schemas/RepositoryScoped.ts";
import { UseCaseFailure } from "../schemas/failures/index.ts";
import type { UseCaseContract, UseCaseMeta } from "./Types.ts";

export { UseCaseFailure, UseCaseFailureTag } from "../schemas/failures/index.ts";

const NonEmptyTrimmedString = Schema.String.check(
  Schema.makeFilter<string>((value) => value.trim().length > 0 || "a non-empty string", {
    expected: "a non-empty string",
  }),
);

const RepositoryScopedEmpty = RepositoryScoped(EmptyInput);
const RepositoryScopedString = RepositoryScoped(Schema.String);
const RepositoryScopedIssueId = RepositoryScoped(
  Schema.Struct({
    id: Schema.String,
  }),
);

const contract = <
  const Name extends string,
  InputSchema extends Schema.Top,
  SuccessSchema extends Schema.Top,
  const Aliases extends ReadonlyArray<string>,
>(
  input: Omit<
    UseCaseContract<Name, InputSchema, SuccessSchema, typeof UseCaseFailure>,
    "aliases" | "failureSchema" | "version"
  > & {
    readonly aliases: Aliases;
  },
): UseCaseContract<Name, InputSchema, SuccessSchema, typeof UseCaseFailure> & {
  readonly aliases: Aliases;
} => ({
  ...input,
  failureSchema: UseCaseFailure,
  version: "0.1.0",
});

export const UseCaseContracts = {
  RepositoryOpen: contract({
    aliases: [],
    category: "repository",
    description: "Open or register a repository with the Cycle read model.",
    idempotency: "supported",
    inputSchema: RepositoryOpenInput,
    name: "RepositoryOpen",
    repositoryScope: "single",
    sideEffect: "sync",
    successSchema: RepositoryStatus,
  }),
  RepositoryClose: contract({
    aliases: [],
    category: "repository",
    description: "Close an opened repository.",
    idempotency: "not-supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryClose",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: Schema.Undefined,
  }),
  RepositoryList: contract({
    aliases: ["repository.status.list"],
    category: "repository",
    description: "List repository statuses.",
    idempotency: "read-only",
    inputSchema: EmptyInput,
    name: "RepositoryList",
    repositoryScope: "none",
    sideEffect: "read",
    successSchema: Schema.Array(RepositoryStatus),
  }),
  RepositoryStatusGet: contract({
    aliases: ["repository.status.get"],
    category: "repository",
    description: "Read one repository status.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryStatusGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: RepositoryStatus,
  }),
  RepositoryMaterializationWarningsList: contract({
    aliases: ["repository.materializationWarnings"],
    category: "repository",
    description: "List materialization warnings for a repository.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryMaterializationWarningsList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.Array(MaterializationWarning),
  }),
  RepositorySync: contract({
    aliases: ["repository.sync"],
    category: "repository",
    description: "Synchronize the local repository projection.",
    idempotency: "supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositorySync",
    repositoryScope: "single",
    sideEffect: "sync",
    successSchema: RepositoryStatus,
  }),
  RepositoryPush: contract({
    aliases: ["repository.push"],
    category: "repository",
    description: "Push Cycle refs for a repository.",
    idempotency: "not-supported",
    inputSchema: RepositoryScopedEmpty,
    name: "RepositoryPush",
    repositoryScope: "single",
    sideEffect: "push",
    successSchema: SyncResult,
  }),
  RepositoryHistoryList: contract({
    aliases: ["repository.history.list"],
    category: "repository",
    description: "List repository history commits.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(RepositoryHistoryInput),
    name: "RepositoryHistoryList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: HistoryPage,
  }),
  InboxList: contract({
    aliases: ["inbox.list"],
    category: "inbox",
    description: "List local inbox items for a user.",
    idempotency: "read-only",
    inputSchema: InboxQuery,
    name: "InboxList",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: InboxPage,
  }),
  InboxSummaryGet: contract({
    aliases: ["inbox.summary"],
    category: "inbox",
    description: "Read local inbox counts and repository projection state for a user.",
    idempotency: "read-only",
    inputSchema: InboxSummaryQuery,
    name: "InboxSummaryGet",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: InboxSummary,
  }),
  InboxMarkRead: contract({
    aliases: ["inbox.markRead"],
    category: "inbox",
    description: "Mark local inbox items read for a user.",
    idempotency: "supported",
    inputSchema: InboxMutationInput,
    name: "InboxMarkRead",
    repositoryScope: "multi",
    sideEffect: "write",
    successSchema: InboxMutationResult,
  }),
  InboxMarkUnread: contract({
    aliases: ["inbox.markUnread"],
    category: "inbox",
    description: "Mark local inbox items unread for a user.",
    idempotency: "supported",
    inputSchema: InboxMutationInput,
    name: "InboxMarkUnread",
    repositoryScope: "multi",
    sideEffect: "write",
    successSchema: InboxMutationResult,
  }),
  InboxArchive: contract({
    aliases: ["inbox.archive"],
    category: "inbox",
    description: "Archive local inbox items for a user.",
    idempotency: "supported",
    inputSchema: InboxMutationInput,
    name: "InboxArchive",
    repositoryScope: "multi",
    sideEffect: "write",
    successSchema: InboxMutationResult,
  }),
  IssueCreate: contract({
    aliases: ["ticket.issue.create"],
    category: "issue",
    description: "Create a committed issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(CreateIssueInput),
    name: "IssueCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueGet: contract({
    aliases: ["ticket.issue.get"],
    category: "issue",
    description: "Read one issue.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueIdInput),
    name: "IssueGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(TicketDocument),
  }),
  IssueList: contract({
    aliases: ["ticket.issue.list"],
    category: "issue",
    description: "List issues.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueQuery),
    name: "IssueList",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: TicketPage,
  }),
  IssueSearch: contract({
    aliases: ["ticket.issue.search"],
    category: "issue",
    description: "Search issues.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(SearchTicketsInput),
    name: "IssueSearch",
    repositoryScope: "multi",
    sideEffect: "read",
    successSchema: TicketSearchPage,
  }),
  IssueUpdate: contract({
    aliases: ["ticket.issue.update"],
    category: "issue",
    description: "Update issue frontmatter or body.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpdateIssueRequestInput),
    name: "IssueUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueTransition: contract({
    aliases: ["ticket.issue.transition"],
    category: "issue",
    description: "Transition issue status.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(TransitionIssueInput),
    name: "IssueTransition",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueArchive: contract({
    aliases: ["ticket.issue.archive"],
    category: "issue",
    description: "Archive an issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(ArchiveIssueInput),
    name: "IssueArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueRestore: contract({
    aliases: ["ticket.issue.restore"],
    category: "issue",
    description: "Restore an archived or deleted issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(RestoreIssueInput),
    name: "IssueRestore",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueDelete: contract({
    aliases: ["ticket.issue.delete"],
    category: "issue",
    description: "Soft-delete an issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(DeleteIssueInput),
    name: "IssueDelete",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueHistoryList: contract({
    aliases: ["ticket.issue.history"],
    category: "issue",
    description: "List issue history commits.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueHistoryInput),
    name: "IssueHistoryList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: HistoryPage,
  }),
  IssueRevisionGet: contract({
    aliases: ["ticket.issue.revision.get"],
    category: "issue",
    description: "Read an issue at a snapshot.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueRevisionInput),
    name: "IssueRevisionGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(TicketDocument),
  }),
  IssueDiff: contract({
    aliases: ["ticket.issue.diff"],
    category: "issue",
    description: "Read an issue diff between two snapshots.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueDiffInput),
    name: "IssueDiff",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: TicketRevisionDiff,
  }),
  IssueRelationAdd: contract({
    aliases: ["ticket.issue.relation.add", "ticket.issue.dependency.add"],
    category: "issue",
    description: "Add an issue relation.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(RelationIssueInput),
    name: "IssueRelationAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueRelationRemove: contract({
    aliases: ["ticket.issue.relation.remove", "ticket.issue.dependency.remove"],
    category: "issue",
    description: "Remove an issue relation.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(RelationIssueInput),
    name: "IssueRelationRemove",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  IssueRelationList: contract({
    aliases: ["ticket.issue.relation.list", "ticket.issue.dependency.list"],
    category: "issue",
    description: "List an issue's dependency and related-ticket edges.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueIdInput),
    name: "IssueRelationList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.Array(IssueRelation),
  }),
  DraftCreate: contract({
    aliases: ["ticket.draft.create"],
    category: "draft",
    description: "Create a draft issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(CreateDraftInput),
    name: "DraftCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDraftDocument,
  }),
  DraftUpdate: contract({
    aliases: ["ticket.draft.update"],
    category: "draft",
    description: "Update a draft issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpdateDraftInput),
    name: "DraftUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDraftDocument,
  }),
  DraftCommit: contract({
    aliases: ["ticket.draft.commit"],
    category: "draft",
    description: "Commit a draft issue.",
    idempotency: "not-supported",
    inputSchema: RepositoryScopedString,
    name: "DraftCommit",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  CommentAdd: contract({
    aliases: [],
    category: "record",
    description: "Add a user-visible issue comment.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(
      Schema.Struct({
        body: NonEmptyTrimmedString,
        issueId: Schema.String,
      }),
    ),
    name: "CommentAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: LinkedRecord,
  }),
  RecordAdd: contract({
    aliases: ["ticket.record.add"],
    category: "record",
    description: "Add a linked record.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(AddLinkedRecordInput),
    name: "RecordAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: LinkedRecord,
  }),
  RecordListForIssue: contract({
    aliases: ["ticket.record.listForIssue"],
    category: "record",
    description: "List records for an issue.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(RecordsForIssueInput),
    name: "RecordListForIssue",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: RecordPage,
  }),
  InitiativeCreate: contract({
    aliases: ["ticket.initiative.create"],
    category: "initiative",
    description: "Create an initiative.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(CreateIssueInput),
    name: "InitiativeCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: TicketDocument,
  }),
  InitiativeProgressGet: contract({
    aliases: ["ticket.initiative.progress"],
    category: "initiative",
    description: "Read initiative progress.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedIssueId,
    name: "InitiativeProgressGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: InitiativeProgress,
  }),
  InitiativeUpdateAdd: contract({
    aliases: ["ticket.initiative.update.add"],
    category: "initiative",
    description: "Add an initiative update.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(AddInitiativeUpdateRequestInput),
    name: "InitiativeUpdateAdd",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: LinkedRecord,
  }),
  LabelList: contract({
    aliases: ["ticket.label.list"],
    category: "label",
    description: "List labels.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(LabelDefinitionQuery),
    name: "LabelList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: LabelDefinitionPage,
  }),
  LabelUpsert: contract({
    aliases: ["ticket.label.upsert"],
    category: "label",
    description: "Create or update a label.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpsertLabelInput),
    name: "LabelUpsert",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: LabelDefinitionDocument,
  }),
  LabelArchive: contract({
    aliases: ["ticket.label.archive"],
    category: "label",
    description: "Archive a label.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(LabelIdInput),
    name: "LabelArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: LabelDefinitionDocument,
  }),
  UserGet: contract({
    aliases: ["ticket.user.get"],
    category: "user",
    description: "Read one user.",
    idempotency: "read-only",
    inputSchema: RepositoryScopedString,
    name: "UserGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(UserProfileDocument),
  }),
  UserList: contract({
    aliases: ["ticket.user.list"],
    category: "user",
    description: "List users.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(UserProfileQuery),
    name: "UserList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: UserProfilePage,
  }),
  UserUpsert: contract({
    aliases: ["ticket.user.upsert"],
    category: "user",
    description: "Create or update a user.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpsertUserInput),
    name: "UserUpsert",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: UserProfileDocument,
  }),
  ViewCreate: contract({
    aliases: ["ticket.view.create"],
    category: "view",
    description: "Create a saved view.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(CreateSavedViewInput),
    name: "ViewCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: SavedViewDocument,
  }),
  ViewGet: contract({
    aliases: ["ticket.view.get"],
    category: "view",
    description: "Read one saved view.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(ViewIdInput),
    name: "ViewGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(SavedViewDocument),
  }),
  ViewList: contract({
    aliases: ["ticket.view.list"],
    category: "view",
    description: "List saved views.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(SavedViewQuery),
    name: "ViewList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: SavedViewPage,
  }),
  ViewUpdate: contract({
    aliases: ["ticket.view.update"],
    category: "view",
    description: "Update a saved view.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpdateViewRequestInput),
    name: "ViewUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: SavedViewDocument,
  }),
  ViewDelete: contract({
    aliases: ["ticket.view.delete"],
    category: "view",
    description: "Delete a saved view.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(ViewIdInput),
    name: "ViewDelete",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: SavedViewDocument,
  }),
  TemplateCreate: contract({
    aliases: ["ticket.template.create"],
    category: "template",
    description: "Create an issue template.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(CreateIssueTemplateInput),
    name: "TemplateCreate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: IssueTemplateDocument,
  }),
  TemplateGet: contract({
    aliases: ["ticket.template.get"],
    category: "template",
    description: "Read one issue template.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(TemplateIdInput),
    name: "TemplateGet",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: Schema.NullOr(IssueTemplateDocument),
  }),
  TemplateList: contract({
    aliases: ["ticket.template.list"],
    category: "template",
    description: "List issue templates.",
    idempotency: "read-only",
    inputSchema: RepositoryScoped(IssueTemplateQuery),
    name: "TemplateList",
    repositoryScope: "single",
    sideEffect: "read",
    successSchema: IssueTemplatePage,
  }),
  TemplateUpdate: contract({
    aliases: ["ticket.template.update"],
    category: "template",
    description: "Update an issue template.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(UpdateTemplateRequestInput),
    name: "TemplateUpdate",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: IssueTemplateDocument,
  }),
  TemplateArchive: contract({
    aliases: ["ticket.template.archive"],
    category: "template",
    description: "Archive an issue template.",
    idempotency: "not-supported",
    inputSchema: RepositoryScoped(TemplateIdInput),
    name: "TemplateArchive",
    repositoryScope: "single",
    sideEffect: "write",
    successSchema: IssueTemplateDocument,
  }),
  AutomationEvaluateRepository: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate repository-level automation checks.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateRepositoryInput,
    name: "AutomationEvaluateRepository",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: AutomationEvaluation,
  }),
  AutomationEvaluateIssues: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate automation checks for explicit issues.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateIssuesInput,
    name: "AutomationEvaluateIssues",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: AutomationEvaluation,
  }),
  AutomationEvaluateQuery: contract({
    aliases: [],
    category: "automation",
    description: "Evaluate automation checks for a query.",
    idempotency: "read-only",
    inputSchema: AutomationEvaluateQueryInput,
    name: "AutomationEvaluateQuery",
    repositoryScope: "single",
    sideEffect: "evaluate",
    successSchema: AutomationEvaluation,
  }),
} as const satisfies Record<string, UseCaseContract>;

export type UseCaseName = keyof typeof UseCaseContracts;
export type UseCaseInput<Name extends UseCaseName> =
  (typeof UseCaseContracts)[Name]["inputSchema"]["Type"];
export type UseCaseSuccess<Name extends UseCaseName> =
  (typeof UseCaseContracts)[Name]["successSchema"]["Type"];

export type CycleUseCase<Name extends UseCaseName = UseCaseName> = {
  readonly input: UseCaseInput<Name>;
  readonly meta?: UseCaseMeta;
  readonly name: Name;
};

const AliasEntries = Object.values(UseCaseContracts).flatMap((contract) =>
  contract.aliases.map((alias) => [alias, contract.name] as const),
);

export type UseCaseAlias = (typeof UseCaseContracts)[UseCaseName]["aliases"][number];
export type UseCaseNameForAlias<Alias extends UseCaseAlias> = {
  readonly [Name in UseCaseName]: Alias extends (typeof UseCaseContracts)[Name]["aliases"][number]
    ? Name
    : never;
}[UseCaseName];
export type UseCaseInputForAlias<Alias extends UseCaseAlias> = UseCaseInput<
  UseCaseNameForAlias<Alias>
>;
export type UseCaseSuccessForAlias<Alias extends UseCaseAlias> = UseCaseSuccess<
  UseCaseNameForAlias<Alias>
>;
export type UseCasePayloadsByAlias = {
  readonly [Alias in UseCaseAlias]: UseCaseInputForAlias<Alias>;
};
export type UseCaseSuccessesByAlias = {
  readonly [Alias in UseCaseAlias]: UseCaseSuccessForAlias<Alias>;
};
type UseCasePayloadSchemasByAlias = {
  readonly [Alias in UseCaseAlias]: (typeof UseCaseContracts)[UseCaseNameForAlias<Alias>]["inputSchema"];
};
type UseCaseSuccessSchemasByAlias = {
  readonly [Alias in UseCaseAlias]: (typeof UseCaseContracts)[UseCaseNameForAlias<Alias>]["successSchema"];
};

export const UseCaseAliases = new Map<string, UseCaseName>(AliasEntries);
export const UseCaseAliasList = AliasEntries.map(([alias]) => alias) as ReadonlyArray<UseCaseAlias>;
export const UseCasePayloadSchemasByAlias = Object.fromEntries(
  AliasEntries.map(([alias, name]) => [alias, UseCaseContracts[name].inputSchema]),
) as UseCasePayloadSchemasByAlias;
export const UseCaseSuccessSchemasByAlias = Object.fromEntries(
  AliasEntries.map(([alias, name]) => [alias, UseCaseContracts[name].successSchema]),
) as UseCaseSuccessSchemasByAlias;

export const contractFor = <Name extends UseCaseName>(
  name: Name,
): (typeof UseCaseContracts)[Name] => UseCaseContracts[name];

export const useCaseNameForAlias = (alias: string): UseCaseName | null =>
  UseCaseAliases.get(alias) ?? null;

export const contractForAlias = <Alias extends UseCaseAlias>(
  alias: Alias,
): (typeof UseCaseContracts)[UseCaseNameForAlias<Alias>] => {
  const name = useCaseNameForAlias(alias);

  if (name === null) {
    throw new Error(`Unsupported usecase alias: ${alias}`);
  }

  return contractFor(name as UseCaseNameForAlias<Alias>);
};
