#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, "..");

const args = process.argv.slice(2);

const readArgValue = (name, fallback) => {
  const prefix = `${name}=`;
  const inline = args.find((arg) => arg.startsWith(prefix));
  if (inline !== undefined) return inline.slice(prefix.length);

  const index = args.indexOf(name);
  if (index >= 0 && args[index + 1] !== undefined) return args[index + 1];

  return fallback;
};

const hasFlag = (name) => args.includes(name);

const codex = readArgValue("--codex", process.env.CODEX_BIN ?? "codex");
const out = resolve(packageRoot, readArgValue("--out", "src/_generated"));
const generateTs = !hasFlag("--skip-ts");
const generateJsonSchema = hasFlag("--json-schema") || hasFlag("--generate-json-schema");

mkdirSync(out, { recursive: true });

const run = (label, commandArgs) => {
  console.log(`Generating Codex app-server ${label}...`);
  const result = spawnSync(codex, commandArgs, {
    cwd: packageRoot,
    env: process.env,
    stdio: "inherit",
  });

  if (result.error !== undefined) {
    console.error(`Failed to run ${codex}: ${result.error.message}`);
    process.exit(1);
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
};

const generatedTypeScriptFiles = (directory) =>
  readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return generatedTypeScriptFiles(path);
    return entry.isFile() && entry.name.endsWith(".ts") ? [path] : [];
  });

const normalizeRelativeTypeScriptSpecifier = (file, specifier) => {
  if (!specifier.startsWith(".")) return specifier;
  if (/\.(?:js|json|ts)$/u.test(specifier)) return specifier;

  const target = resolve(dirname(file), specifier);
  if (existsSync(`${target}.ts`)) return `${specifier}.ts`;
  if (existsSync(resolve(target, "index.ts"))) return `${specifier}/index.ts`;
  return specifier;
};

const normalizeGeneratedTypeScriptImports = () => {
  if (!generateTs) return;

  let changed = 0;
  for (const file of generatedTypeScriptFiles(out)) {
    const source = readFileSync(file, "utf8");
    const next = source
      .replace(/(from\s+["'])(\.[^"']+)(["'])/gu, (_match, prefix, specifier, suffix) => {
        const normalized = normalizeRelativeTypeScriptSpecifier(file, specifier);
        return `${prefix}${normalized}${suffix}`;
      })
      .replace(/(import\s+["'])(\.[^"']+)(["'])/gu, (_match, prefix, specifier, suffix) => {
        const normalized = normalizeRelativeTypeScriptSpecifier(file, specifier);
        return `${prefix}${normalized}${suffix}`;
      });

    if (next === source) continue;
    writeFileSync(file, next);
    changed += 1;
  }

  if (changed > 0) {
    console.log(`Normalized explicit .ts imports in ${changed} generated files.`);
  }
};

const commands = [];

if (generateTs) {
  commands.push(["app-server", "generate-ts", "--out", out]);
}
if (generateJsonSchema) {
  commands.push(["app-server", "generate-json-schema", "--out", out]);
}
if (commands.length === 0) {
  console.log("Nothing to generate; --skip-ts was provided without --json-schema.");
  process.exit(0);
}

for (const commandArgs of commands) {
  run(commandArgs[1], commandArgs);
}

normalizeGeneratedTypeScriptImports();

writeFileSync(
  resolve(out, "cycle-generation-manifest.json"),
  `${JSON.stringify(
    {
      commands: commands.map((commandArgs) => [codex, ...commandArgs].join(" ")),
      generatedAt: new Date().toISOString(),
      note: "Generated by packages/codex-app-server/scripts/generate.mjs. Outputs are specific to the installed Codex version.",
    },
    null,
    2,
  )}\n`,
);

console.log(`Codex app-server protocol artifacts written to ${out}`);
