import { Schema } from "effect";
import { AgentJsonObject, AgentTimestamp } from "./AgentCommon.ts";
import {
  AgentAttemptId,
  AgentEventId,
  AgentRunId,
  AgentTaskId,
  AgentThreadId,
  AgentTurnId,
} from "./AgentIds.ts";
import { AgentVisibility } from "./AgentMessage.ts";

export const AgentEventType = Schema.Literals([
  "thread.opened",
  "thread.settings-updated",
  "thread.summarized",
  "thread.archived",
  "thread.retention-changed",
  "task.submitted",
  "task.queued",
  "task.claimed",
  "task.preparing",
  "task.started",
  "task.suspending",
  "task.suspended",
  "task.resuming",
  "task.retry-scheduled",
  "task.cancelling",
  "task.completed",
  "task.failed",
  "task.cancelled",
  "run.queued",
  "run.started",
  "run.suspended",
  "run.resumed",
  "run.completed",
  "run.failed",
  "run.cancelled",
  "attempt.claimed",
  "attempt.provider-attached",
  "attempt.heartbeat",
  "attempt.interrupted",
  "attempt.completed",
  "attempt.failed",
  "attempt.cancelled",
  "turn.started",
  "turn.completed",
  "turn.failed",
  "message.started",
  "message.delta",
  "message.completed",
  "message.failed",
  "reasoning.started",
  "reasoning.delta",
  "reasoning.completed",
  "tool.started",
  "tool.progress",
  "tool.completed",
  "tool.rejected",
  "tool.failed",
  "command.started",
  "command.output",
  "command.completed",
  "approval.requested",
  "approval.resolved",
  "user-input.requested",
  "user-input.resolved",
  "steering.accepted",
  "steering.queued",
  "steering.rejected",
  "child.requested",
  "child.queued",
  "child.started",
  "child.completed",
  "child.failed",
  "child.cancelled",
  "workflow.started",
  "workflow.completed",
  "workflow.retried",
  "workflow.failed",
  "workflow.compensated",
  "workspace.requested",
  "workspace.ready",
  "workspace.acquired",
  "workspace.released",
  "workspace.retained",
  "workspace.failed",
  "artifact.recorded",
  "usage.reported",
  "warning.reported",
  "error.recoverable",
  "reconciliation.started",
  "reconciliation.reattached",
  "reconciliation.replayed",
  "reconciliation.retried",
  "reconciliation.suspended",
  "reconciliation.failed",
  "retention.compacted",
]);
export type AgentEventType = typeof AgentEventType.Type;

export const AgentEventRetention = Schema.Literals([
  "permanent",
  "delta-24h",
  "debug-30d",
  "diagnostic-7d",
]);
export type AgentEventRetention = typeof AgentEventRetention.Type;

export class AgentRuntimeEvent extends Schema.Class<AgentRuntimeEvent>(
  "@cycle/agents/AgentRuntimeEvent",
)({
  attemptId: Schema.optional(AgentAttemptId),
  eventId: AgentEventId,
  eventType: AgentEventType,
  occurredAt: AgentTimestamp,
  parentRunId: Schema.optional(AgentRunId),
  payload: AgentJsonObject,
  persistedAt: AgentTimestamp,
  retention: AgentEventRetention,
  rootRunId: Schema.optional(AgentRunId),
  runId: Schema.optional(AgentRunId),
  schemaVersion: Schema.Literal(1),
  sequence: Schema.Int.check(Schema.isGreaterThanOrEqualTo(1)),
  taskId: Schema.optional(AgentTaskId),
  threadId: AgentThreadId,
  turnId: Schema.optional(AgentTurnId),
  visibility: AgentVisibility,
}) {}

export class AgentEventAppend extends Schema.Class<AgentEventAppend>(
  "@cycle/agents/AgentEventAppend",
)({
  attemptId: Schema.optional(AgentAttemptId),
  eventId: AgentEventId,
  eventType: AgentEventType,
  occurredAt: AgentTimestamp,
  parentRunId: Schema.optional(AgentRunId),
  payload: AgentJsonObject,
  retention: AgentEventRetention,
  rootRunId: Schema.optional(AgentRunId),
  runId: Schema.optional(AgentRunId),
  taskId: Schema.optional(AgentTaskId),
  threadId: AgentThreadId,
  turnId: Schema.optional(AgentTurnId),
  visibility: AgentVisibility,
}) {}
