export type {
  HistoryCommit,
  HistoryPage,
  InboxEntry,
  InboxMutationResult,
  InboxPage,
  InboxRepositorySummary,
  InboxSummary,
  InitiativeProgress,
  IssueRelation,
  IssueTemplateDocument,
  IssueTemplatePage,
  LabelDefinitionDocument,
  LabelDefinitionPage,
  LinkedRecord,
  MaterializationWarning,
  RecordPage,
  RepositoryMetadata,
  RepositoryStatus,
  SavedViewDocument,
  SavedViewPage,
  SyncResult,
  TicketDocument,
  TicketDraftDocument,
  TicketPage,
  TicketRevisionDiff,
  TicketSearchPage,
  UserProfileDocument,
  UserProfilePage,
} from "./schemas/entities/index.ts";
export type {
  AddLinkedRecordInput as AddRecordInput,
  ArchiveIssueInput as ArchiveTicketInput,
  CreateDraftInput as CreateTicketDraftInput,
  CreateIssueInput as CreateTicketInput,
  CreateIssueTemplateInput,
  CreateSavedViewInput,
  DeleteIssueInput as DeleteTicketInput,
  InboxMutationInput,
  InboxQuery,
  InboxReason,
  InboxStatus,
  InitiativeUpdateInput as InitiativeUpdatePayload,
  IssueQuery as TicketQuery,
  IssueTemplateQuery,
  LabelDefinitionQuery,
  RecordQuery,
  RepositoryHistoryInput as RepositoryHistoryQuery,
  RepositoryOpenInput as RepositoryInput,
  RestoreIssueInput as RestoreTicketInput,
  SavedViewQuery,
  SearchTicketsInput as SearchTicketsQuery,
  TransitionIssueInput as TransitionTicketInput,
  UpdateDraftInput as UpdateTicketDraftInput,
  UpdateIssueInput as UpdateTicketPatch,
  UpdateIssueTemplateInput as UpdateIssueTemplatePatch,
  UpdateSavedViewInput as UpdateSavedViewPatch,
  UpsertLabelInput as UpsertLabelDefinitionInput,
  UpsertUserInput as CreateOrUpdateUserProfileInput,
  UserProfileQuery,
} from "./schemas/api/requests/index.ts";

export type AddCommentInput = {
  readonly body: string;
  readonly issueId: string;
};
