// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerInfo } from "../McpServerInfo.ts";
import type { Resource } from "../Resource.ts";
import type { ResourceTemplate } from "../ResourceTemplate.ts";
import type { Tool } from "../Tool.ts";
import type { McpAuthStatus } from "./McpAuthStatus.ts";

export type McpServerStatus = { name: string, serverInfo: McpServerInfo | null, tools: { [key in string]?: Tool }, resources: Array<Resource>, resourceTemplates: Array<ResourceTemplate>, authStatus: McpAuthStatus, };
