// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.ts";
import type { OverriddenMetadata } from "./OverriddenMetadata.ts";
import type { WriteStatus } from "./WriteStatus.ts";

export type ConfigWriteResponse = { status: WriteStatus, version: string,
/**
 * Canonical path to the config file that was written.
 */
filePath: AbsolutePathBuf, overriddenMetadata: OverriddenMetadata | null, };
