// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue.ts";
import type { MergeStrategy } from "./MergeStrategy.ts";

export type ConfigEdit = { keyPath: string, value: JsonValue, mergeStrategy: MergeStrategy, };
