// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandMigration } from "./CommandMigration.ts";
import type { HookMigration } from "./HookMigration.ts";
import type { McpServerMigration } from "./McpServerMigration.ts";
import type { PluginsMigration } from "./PluginsMigration.ts";
import type { SessionMigration } from "./SessionMigration.ts";
import type { SubagentMigration } from "./SubagentMigration.ts";

export type MigrationDetails = { plugins: Array<PluginsMigration>, sessions: Array<SessionMigration>, mcpServers: Array<McpServerMigration>, hooks: Array<HookMigration>, subagents: Array<SubagentMigration>, commands: Array<CommandMigration>, };
