// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.ts";
import type { AppSummary } from "./AppSummary.ts";
import type { AppTemplateSummary } from "./AppTemplateSummary.ts";
import type { PluginHookSummary } from "./PluginHookSummary.ts";
import type { PluginSummary } from "./PluginSummary.ts";
import type { SkillSummary } from "./SkillSummary.ts";

export type PluginDetail = { marketplaceName: string, marketplacePath: AbsolutePathBuf | null, summary: PluginSummary, description: string | null, skills: Array<SkillSummary>, hooks: Array<PluginHookSummary>, apps: Array<AppSummary>, appTemplates: Array<AppTemplateSummary>, mcpServers: Array<string>, };
